### ISSUE TITLE
Firefox is missing in dev container

### ISSUE THREAD

**Issue by cambamf** [smanders/buildpro#29]
When I start up the dev container, it doesn't have firefox. Can we add it to the dev container as it is already in the runtime container?

**Comment by smanders** [comment]
chrome is going to be added to the bld image, so we can run web unit tests in a bld container
this will make chrome also available in a dev container, since the dev image is built on top of the bld image
firefox (and chrome) will both continue to be in the run image
so this isn't fulfilling this request to have firefox in the dev image, but there will be a browser in the dev image... hopefully "good enough"

closing as won't fix
