### ISSUE TITLE
Request for tools to be added to a dev/runtime container

### ISSUE THREAD

**Issue by detomno** [smanders/buildpro#96]
It would be nice to have a consistent dev environment for the plugin developers where all of the typical dev tools would be available.  This would save some time for individual developers to find and copy over tools that will be typically used.

For CI and CM we'd want to keep the size of the container down as much as possible, as such we're looking for a second container where development can happen and all the tools used by Plugin developers would be installed and ready to use.  

Tools/Libraries requested
Internal: IQT, ICT, PluginEmulator, Sarpyvalidator, BmvTool
External: Perf, Nvidia-nsight, Cuda-gdb (as a minimum, but since this likely wouldn't be the build container it's probably worth it to deal with the bloat of including all the cuda toolkit libraries)

Final details would be based on design that happens.

**Comment by smanders** [comment]
I'm seeing a request for 2 docker buildpro images here, so please correct me if I'm misinterpreting this
1. minimal image with only the set of packages needed to build plugins and PluginSdk (the rocky85-pin.dockerfile of the 24.10 release https://github.com/externpro/buildpro/blob/24.10/public/rocky85-pin.dockerfile)
1. plugin developer image that has the entire cuda-toolkit installed (what I am likely to call rocky85-pdv for "plugin development/developer")
   * does the cuda-toolkit include Nvidia-nsight and Cuda-gdb? because I haven't seen anything from you guys that provides a link to where these can be obtained separately)
   * all publicly available packages will be part of the publicly available rocky85-pdv image
   * internal tools (only available on isrhub) will be built into a local docker image (and not published to a container registery) the same way CRTool and webpro are handled today -- we can determine where the denv.sh script will look for what version of these tools to install (could be in PluginLibraries so everything uses the same version or could be controlled by each plugin independently)
   * rocky85-pdv could ditch LaTeX and perhaps a few other packages (doxygen? lcov for coverage? others?) that are in rocky85-pin if plugin developers aren't likely to utilize the functionality they provide but are required for CI and officially building the software)

perf is small and easy to obtain with dnf, so I may include it in both rocky85-pin and rocky85-pdv

I'll consult with @camerbam to learn whether VantageCI relies on `docker-compose.sh -g` to start a GPU container to run plugin device_test's -- perhaps the -g option can be the mechanism for a developer to start a container based on the rocky85-pdv image https://github.com/externpro/externpro/blob/24.10/compose.gpu.yml#L48 or I may need to add another option to the compose.gpu.[sh|yml] to support starting up a container that's based on the rocky85-pdv image https://github.com/externpro/externpro/blob/24.10/compose.gpu.sh#L10

**Comment by smanders** [comment]
also, just to clarify on the issue title "Request for tools to be added to a dev/runtime container" -- I'm assuming you aren't asking for a dev and a runtime container (I'm going to call it an image from here on out because the dockerfile that will specify all these requested tools will build a docker image and it becomes a container when instantiated) -- that instead of asking for two images (dev and runtime) you are asking for a single image and you didn't know whether to call it a dev or a runtime image

I would prefer to reserve any use of the word "runtime" to an image that doesn't include *any* developer tools or packages... just the base Rocky image and any packages that are necessary for a plugin to run (using the CI-produced plugin tar.xz) -- this is what VantageDocker provides for our microservices: a runtime image -- and if the plugin team desires something similar I would suggest this should be separate and independent of buildpro-based docker images

**Comment by detomno** [comment]
1. Yes, I'm looking for 2 different images.  Buildpro was acceptable as the small light weight image, but if a plugin specific build image is easy to make and maintain that would be a good option.
2. I'd have to check with Levi/Blake again, but I believe that the cuda toolkit would contain the cuda-gdb and a cuda-nisight.  I'm unfortunatley out tomorrow, but I'll get with them to get the answers to your question and update on Monday.
 - Latex we should be able to remove.  We don't build any pdfs and release them with our products.  I don't think we use doxygen at all.  We do still run and look at the unit test line coverages to focus on where we need to improve our unit tests.  I'll have to take a look at the other packages that are currently included to see if any more could be dropped.

I was a little unclear on the image/container.  I remember having the conversation with you before about these definitions, but when you had said that we have an image and then load up the internal tools (like CRTool) it made it sound like CRTool was not part of the image, but it would be part of the container.  Clearly there's more to the definitions that I didn't pick up on.  As to runtime vs dev images, we hadn't needed to deal with the distinction previously so I wasn't aware.  The title was left general so that you could provide a suggested solution without forcing you to work within a limited scope, or my limited understanding.    Given your context, we would be asking for a dev image that would contain the tools we would use to write and test our code.

**Comment by smanders** [comment]
> Buildpro was acceptable as the small light weight image

I'm going to clarify this, because using the term "Buildpro" is not specific enough to have any meaning here -- I'm assuming you're referring to the `-bld` image from before the last release (24.10)... so this image https://github.com/externpro/buildpro/blob/24.09/public/rocky85-bld.dockerfile

and yeah, as of the 24.10 release plugins no longer use the `-bld` image -- the `-bld` image is now the much more lightweight image used for building vantage microservices

as of the 24.10 release the `-pin` image is now the minimal amount of packages needed to build plugins and the PluginSdk

going forward the `-pin` image will remain the same (minimal amount of packages needed to build plugins and PluginSdk) and a new `pdv` image will contain packages requested for plugin development purposes

LaTeX is necessary to build the PluginSdk. So you are correct that no plugin products use LaTeX, but we do have a (plugin-related) product (PluginSdk) that does require LaTeX.

Regarding image vs container: anything specified in a dockerfile is going to create a docker image. When that image is instantiated by docker compose (if you're using the provided docker-compose.sh script), it becomes a container.

I'm not sure why you closed this issue... but it's okay for it to remain closed -- I'll take the information you provided here and compose other issues that the changes will reference

**Comment by detomno** [comment]
I was trying to get out the door last Thursday and my browser was acting really slow.  I had an edit I was trying to make before I left.  I must have accidentally hit the close.  Since we're moving forward with https://github.com/externpro/buildpro/issues/95 I'll leave it closed.

> does the cuda-toolkit include Nvidia-nsight and Cuda-gdb?

Levi said the Cuda toolkit does include both of these.

Let us know on this issue or on #95 if you have additional questions.
